# Generated by Django 5.0.1 on 2024-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srigan_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone_no',
            field=models.CharField(max_length=13),
        ),
    ]
