# Generated by Django 5.0.1 on 2024-01-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srigan_app', '0002_alter_admin_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
